/* QUERY DE LA FACTURACION EN UN RANGO DE FECHAS
EN ESTE EJEMPLO,FECFAC '01/10/20' AND '02/10/20'
OJO:UN CLIENTE PUEDE COMPRAR VARIOS TIPOS DE PRODUCTOS*/
SELECT F.CODFAC COD_FACTURA
,F.FECFAC FECHA
,C.NOMCLI CLIENTE
,P.NOMPRO PRODUCTO
,P.PREPRO PRESENTACION
,DF.CANTID CANTIDAD
,P.VALPRO PRECIO
,DF.TAXES 'IGV(%)'
,DF.DSCTO 'DSCTO(%)'
,DF.CANTID*P.VALPRO*(DF.TAXES+100)*(100-DF.DSCTO)/10000 TOTAL
FROM FACTURA F,DTLFACTURA DF,CLIENTES C,PRODUCTO P
WHERE F.CODFAC=DF.CODFAC 
AND DF.CODPRO=P.CODPRO 
AND C.CODCLI=F.CODCLI
AND F.FECFAC BETWEEN '01/10/20' AND '02/10/20'
ORDER BY 1 ASC