/* QUERY DE LA FACTURACION TOTAL DE UN PRODUCTO ESPECIFICO
EN ESTE EJEMPLO ES EL PRODUCTO DE CODPRO='00001'*/
SELECT PT.CODPRO
,PT.NOMPRO PRODUCTO
,PT.PREPRO PRESENTACION 
,SUM(FA.CANTID)CANTIDAD
,PT.VALPRO PRECIO
,FA.TAXES 'IGV(%)'
,FA.DSCTO 'DSCTO(%)'
,(FA.TAXES+100)*(100-FA.DSCTO)*SUM(FA.CANTID)*PT.VALPRO/10000 TOTAL
FROM DTLFACTURA FA ,PRODUCTO PT
WHERE FA.CODPRO=PT.CODPRO
AND PT.CODPRO='00001'
GROUP BY PT.CODPRO,PT.PREPRO,PT.NOMPRO,PT.VALPRO,FA.TAXES,FA.DSCTO
