/* QUERY DEL HISTORIAL DE FACTURACION DE UN CLIENTE ESPECIFICO
EN EL EJEMPLO ES EL CLIENTE DE CODCLI='38282977'
OJO:UN CLIENTE PUEDE COMPRAR VARIOS TIPOS DE PRODUCTOS*/
SELECT F.CODFAC COD_FACTURA
,C.NOMCLI CLIENTE
,P.NOMPRO PRODUCTO
,P.PREPRO PRESENTACION
,DF.CANTID CANTIDAD
,P.VALPRO PRECIO
,DF.TAXES 'IGV(%)'
,DF.DSCTO 'DSCTO(%)'
,DF.CANTID*P.VALPRO*(DF.TAXES+100)*(100-DF.DSCTO)/10000 TOTAL
FROM FACTURA F,DTLFACTURA DF,CLIENTES C,PRODUCTO P
WHERE F.CODFAC=DF.CODFAC 
AND DF.CODPRO=P.CODPRO 
AND C.CODCLI=F.CODCLI
AND C.CODCLI='38282977'
ORDER BY 1 ASC

