/* QUERY DE CLIENTES QUE HAN COMPRADO POR LO MENOS 1 PRODUCTO
OJO:EL CAMPO VALOR_TOTAL ES EL VALOR ACUMULADO DE TODOS LOS PRODUCTOS COMPRADOS POR CADA CLIENTE*/
SELECT CL.CLIENTE,CL.TELEFONO,CL.CORREO,CL.COUNTRY,CL.DIREC DIRECCION,SUM(CL.TOTAL)VALOR_TOTAL FROM 

(SELECT C.NOMCLI CLIENTE,C.CORREO,C.COUNTRY,C.DIREC,C.TELEFONO
,DF.CANTID*P.VALPRO*(DF.TAXES+100)*(100-DF.DSCTO)/10000 TOTAL
FROM FACTURA F,DTLFACTURA DF,CLIENTES C,PRODUCTO P
WHERE F.CODFAC=DF.CODFAC 
AND DF.CODPRO=P.CODPRO 
AND C.CODCLI=F.CODCLI) CL
GROUP BY CL.CLIENTE,CL.CORREO,CL.COUNTRY,CL.DIREC,CL.TELEFONO
ORDER BY 1 ASC  